name: Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: impleri/automatic-skills/build.yml

  bump:
    name: Version Bump
    runs-on: ubuntu-latest
    needs: build
    if: github.event.pull_request.merged == true
    permissions:
      contents: write

    steps:
      - uses: impleri/automatic-skills/version-bump.yml

  publish:
    name: Publish to Maven
    runs-on: ubuntu-latest
    needs: bump

    steps:
      - uses: impleri/automatic-skills/publish.yml
        with:
          maven-user: ${{ secrets.MAVEN_USER }}
          maven-password: ${{ secrets.MAVEN_TOKEN }}
          modrinth-id: ${{ secrets.MODRINTH_ID }}
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          curseforge-id: ${{ secrets.CURSEFORGE_ID }}
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
