name: 'Check Versioning Label'
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - labeled
      - unlabeled
jobs:
  add_label:
    uses: impleri/automatic-skills/add-label.yml

  check_labels:
    uses: impleri/automatic-skills/check-labels.yml
